In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import Funciones_MCF as MCF
from scipy.stats import kurtosis, skew

/Users/jonathanpena/anaconda3/envs/workShop/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
M7 = ['AAPL','MSFT','NVDA','TSLA']


df_precios = MCF.obtener_datos(M7)
df_precios

YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  4 of 4 completed

Ticker            AAPL        MSFT        NVDA        TSLA
Date
2024-03-06  168.325180  399.043457   88.679016  176.539993
2024-03-07  168.205750  406.040070   92.647072  178.649994
2024-03-08  169.927628  403.142151   87.507301  175.339996
2024-03-11  171.938126  401.455048   85.753708  177.770004
2024-03-12  172.415878  412.133484   91.891266  177.539993
...                ...         ...         ...         ...
2025-02-27  237.300003  392.529999  120.150002  281.950012
2025-02-28  241.839996  396.989990  124.919998  292.980011
2025-03-03  238.029999  388.489990  114.059998  284.649994
2025-03-04  235.929993  388.609985  115.989998  272.040009
2025-03-05  235.740005  401.019989  117.300003  279.100006

[250 rows x 4 columns]

In [3]:
df_rendimientos = MCF.calcular_rendimientos(df_precios)
df_rendimientos

Ticker          AAPL      MSFT      NVDA      TSLA
Date
2024-03-07 -0.000710  0.017533  0.044746  0.011952
2024-03-08  0.010237 -0.007137 -0.055477 -0.018528
2024-03-11  0.011831 -0.004185 -0.020039  0.013859
2024-03-12  0.002779  0.026599  0.071572 -0.001294
2024-03-13 -0.012122 -0.000433 -0.011152 -0.045398
...              ...       ...       ...       ...
2025-02-27 -0.012731 -0.018012 -0.084781 -0.030433
2025-02-28  0.019132  0.011362  0.039700  0.039120
2025-03-03 -0.015754 -0.021411 -0.086936 -0.028432
2025-03-04 -0.008822  0.000309  0.016921 -0.044300
2025-03-05 -0.000805  0.031934  0.011294  0.025952

[249 rows x 4 columns]

In [4]:
promedio_rendi_diario = df_rendimientos['AAPL'].mean()
promedio_rendi_diario

0.0014657776612697613

In [5]:
kurtosis = kurtosis(df_rendimientos['AAPL'])
skew = skew(df_rendimientos['AAPL'])
kurtosis

2.8457020864737634